# Generated by Django 6.0.2 on 2026-02-07 22:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to', models.TextField()),
                ('cc', models.TextField(blank=True)),
                ('bcc', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('text_body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('stripped_reply', models.TextField(blank=True, help_text='Parsed reply text (StrippedTextReply).')),
                ('tag', models.CharField(blank=True, max_length=255)),
                ('mailbox_hash', models.CharField(blank=True, help_text='The +hash portion of the inbound address.', max_length=255)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Complete JSON payload as received from Postmark.')),
                ('date', models.CharField(blank=True, help_text='Original Date header value from the email.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
