# Generated by Django 6.0.2 on 2026-02-08 14:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_id', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to', models.TextField()),
                ('cc', models.TextField(blank=True)),
                ('bcc', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('text_body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('stripped_reply', models.TextField(blank=True, help_text='Parsed reply text (StrippedTextReply).')),
                ('tag', models.CharField(blank=True, max_length=255)),
                ('mailbox_hash', models.CharField(blank=True, help_text='The +hash portion of the inbound address.', max_length=255)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Complete JSON payload as received from Postmark.')),
                ('date', models.CharField(blank=True, help_text='Original Date header value from the email.', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'message_id'), name='unique_user_message')],
            },
        ),
    ]
